{
    "conversation": "Sure, the JC Ontology contains the following significant dates of interest. Hover over each for more information",
    "payload": {
        "knowledge": [
            {
                "holiday": "Rosh Hashanah",
                "duration": "2 days",
                "frequency": "First and second day of the Jewish month of Tishrei",
                "effectiveHours": "Full day",
                "reference": "https://simple.wikipedia.org/wiki/Rosh_Hashanah",
                "exactDates": "Sept 8th & 9th",
                "related": {},
                "policyScore": "",
                "justification": "",
                "religion": "Judaism",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Yom Kippur",
                "duration": "1 day",
                "frequency": "Tenth day of the Jewish month of Tishrei",
                "effectiveHours": "Full day (fasting)",
                "reference": "https://simple.wikipedia.org/wiki/Yom_Kippur",
                "exactDates": "Sept 24th",
                "related": {},
                "policyScore": "",
                "justification": "",
                "religion": "Judaism",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Sukkot",
                "duration": "7-8 days",
                "frequency": "Fifteenth day of Tishrei to twenty-second or twenty-third of Tishrei",
                "effectiveHours": "Varies by day",
                "reference": "https://en.wikipedia.org/wiki/Sukkot",
                "exactDates": "Sept 23rd - Sept 30th or Oct 1st",
                "related": {},
                "policyScore": "",
                "justification": "",
                "religion": "Judaism",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Passover",
                "duration": "7-8 days",
                "frequency": "Fifteenth day of the Jewish month of Nissan",
                "effectiveHours": "Varies by day",
                "reference": "https://simple.wikipedia.org/wiki/Passover",
                "exactDates": "April 8th - April 15th or 16th",
                "related": {},
                "policyScore": "",
                "justification": "",
                "religion": "Judaism",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Shavuot",
                "duration": "1-2 days",
                "frequency": "Sixth and seventh day of the Jewish month of Sivan",
                "effectiveHours": "Full day",
                "reference": "https://simple.wikipedia.org/wiki/Shavuot",
                "exactDates": "May 15th & 16th or 16th only",
                "related": {},
                "policyScore": "",
                "justification": "",
                "religion": "Judaism",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Christmas Day",
                "duration": "1 day",
                "frequency": "December 25th",
                "effectiveHours": "Full day",
                "reference": "https://en.wikipedia.org/wiki/Christmas",
                "exactDates": "December 25th",
                "related": {},
                "policyScore": "",
                "justification": "",
                "religion": "Christianity",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Good Friday",
                "duration": "1 day",
                "frequency": "Friday before Easter Sunday",
                "effectiveHours": "Full day (commemoration)",
                "reference": "https://en.wikipedia.org/wiki/Good_Friday",
                "exactDates": "April 12th",
                "related": {},
                "policyScore": "",
                "justification": "",
                "religion": "Christianity",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Easter Sunday",
                "duration": "1 day",
                "frequency": "First Sunday after the full moon following the vernal equinox",
                "effectiveHours": "Full day",
                "reference": "https://en.wikipedia.org/wiki/Easter",
                "exactDates": "April 14th",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "Christianity",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Eid al-Fitr",
                "duration": "1-3 days",
                "frequency": "First day of the Islamic month of Shawwal",
                "effectiveHours": "Full day",
                "reference": "https://en.wikipedia.org/wiki/Eid_al_Fitr",
                "exactDates": "May 10th or 11th",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "Islam",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Eid al-Adha",
                "duration": "4 days",
                "frequency": "Tenth day of Dhu al-Hijjah (Islamic calendar)",
                "effectiveHours": "Full day",
                "reference": "https://en.wikipedia.org/wiki/Eid_al_Adha",
                "exactDates": "July 19th - 22nd",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "Islam",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Fast of Esther",
                "duration": "1 day",
                "frequency": "13th day of Adar II (Hebrew calendar) - Observance",
                "effectiveHours": "Full day",
                "reference": "https://www.timeanddate.com/holidays/israel/ta-anit-esther",
                "exactDates": "Thursday, March 21",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "Judaism",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Purim Eve",
                "duration": "1 day",
                "frequency": "Eve of Purim - Observance",
                "effectiveHours": "Full day",
                "reference": "https://www.timeanddate.com/holidays/israel/ta-anit-esther",
                "exactDates": "Saturday, March 23",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "Judaism",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Purim (Tel Aviv)",
                "duration": "1 day",
                "frequency": "14th day of Adar II (Hebrew calendar) - Local Holiday",
                "effectiveHours": "Full day",
                "reference": "https://www.timeanddate.com/holidays/israel/ta-anit-esther",
                "exactDates": "Sunday, March 24",
                "related": {},
                "policyScore": "",
                "justification": "",
                "religion": "Judaism",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Shushan Purim (Jerusalem)",
                "duration": "1 day",
                "frequency": "15th day of Adar II (Hebrew calendar) - Local Holiday",
                "effectiveHours": "Varies by day",
                "reference": "https://www.timeanddate.com/holidays/israel/ta-anit-esther",
                "exactDates": "Monday, March 25",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "Judaism",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Passover Eve",
                "duration": "7-8 days",
                "frequency": "14th day of Nisan (Hebrew calendar) - Observance",
                "effectiveHours": "Varies by day",
                "reference": "https://www.hebcal.com/holidays/pesach-2024",
                "exactDates": "Wednesday, April 22",
                "related": {},
                "policyScore": "",
                "justification": "",
                "religion": "Judaism",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Passover (Day 1)",
                "duration": "7-8 days",
                "frequency": "15th day of Nisan (Hebrew calendar) - National Holiday",
                "effectiveHours": "Full day",
                "reference": "https://www.hebcal.com/holidays/pesach-2024",
                "exactDates": "Wednesday, April 23",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "Judaism",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Passover (Day 2)",
                "duration": "7-8 days",
                "frequency": "16th day of Nisan (Hebrew calendar) - Observance",
                "effectiveHours": "Varies",
                "reference": "https://www.hebcal.com/holidays/pesach-2024",
                "exactDates": "Wednesday, April 24",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "Judaism",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Passover (Days 3-4-5)",
                "duration": "7-8 days",
                "frequency": "17th, 18th, 19th days of Nisan (Hebrew calendar) - Observance",
                "effectiveHours": "Varies by day",
                "reference": "https://www.hebcal.com/holidays/pesach-2024",
                "exactDates": "Thursday-Friday-Saturday, April 25-26-27",
                "related": {},
                "policyScore": "",
                "justification": "",
                "religion": "Judaism",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Passover (Days 6-7)",
                "duration": "7-8 days",
                "frequency": "20th, 21st days of Nisan (Hebrew calendar) - Observance",
                "effectiveHours": "Varies by day",
                "reference": "https://www.hebcal.com/holidays/pesach-2024",
                "exactDates": "Sunday-Monday, April 28-29",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "Judaism",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Yom HaShoah",
                "duration": "1 day",
                "frequency": "Holocaust Remembrance Day: Remembers the Jewish victims of the Holocaust - Observance",
                "effectiveHours": "Varies by day",
                "reference": "https://www.timeanddate.com/holidays/israel/yom-hashoah",
                "exactDates": "Monday, May 6",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "Judaism",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Yom HaZikaron",
                "duration": "1 day",
                "frequency": "Israeli Memorial Day: Honors Israeli soldiers and civilians killed in wars and terrorist attacks - Observance",
                "effectiveHours": "Full day",
                "reference": "https://www.hebcal.com/holidays/yom-hazikaron-2024",
                "exactDates": "Monday, May 13",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "Judaism",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Yom HaAtzmaut",
                "duration": "1 day",
                "frequency": "Israeli Independence Day: Celebrates the establishment of the State of Israel - National Holiday",
                "effectiveHours": "Full day",
                "reference": "https://www.timeanddate.com/holidays/israel/yom-haatzmaut",
                "exactDates": "Tuesday, May 14",
                "related": "",
                "policyScore": "low",
                "justification": "",
                "religion": "Judaism",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Lag BaOmer",
                "duration": "1 day",
                "frequency": "33rd day of the Omer counting between Passover and Shavuot - Observance traditionally associated with Rabbi Shimon bar Yochai",
                "effectiveHours": "Full day",
                "reference": "https://www.hebcal.com/holidays/lag-baomer-2024",
                "exactDates": "Sunday, May 26",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "Judaism",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Jerusalem Day",
                "duration": "1 day",
                "frequency": "Reunification of Jerusalem: Marks the reunification of East and West Jerusalem after the Six-Day War in 1967 - Observance",
                "effectiveHours": "Full day",
                "reference": "https://www.timeanddate.com/calendar/custom.html?country=34",
                "exactDates": "Wednesday, June 5",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "Judaism",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Shavuot Eve",
                "duration": "1 day",
                "frequency": "Eve of Shavuot - Observance",
                "effectiveHours": "Full day",
                "reference": "https://www.hebcal.com/holidays/shavuot-2024?i=on",
                "exactDates": "Tuesday, June 11",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "Judaism",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Shavuot",
                "duration": "1 day",
                "frequency": "Festival of Weeks: Celebrates the giving of the Torah on Mount Sinai and the wheat harvest - National Holiday",
                "effectiveHours": "Full day",
                "reference": "https://www.hebcal.com/holidays/shavuot-2024?i=on",
                "exactDates": "Wednesday, June 12",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "Judaism",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Muharram 1 (Islamic New Year)",
                "duration": "1 Day",
                "frequency": "1st day of the Islamic calendar",
                "effectiveHours": "Full Day",
                "reference": "https://en.wikipedia.org/wiki/Islamic_New_Year",
                "exactDates": "",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "Islam",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Ashura",
                "duration": "1 Day",
                "frequency": "10th day of Muharram (commemorates death of Hussein)",
                "effectiveHours": "Varies",
                "reference": "https://simple.wikipedia.org/wiki/Day_of_Ashura",
                "exactDates": "",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "Islam",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Mawlid an-Nabi",
                "duration": "1-3 Days",
                "frequency": "Birthday of the Prophet Muhammad",
                "effectiveHours": "Varies",
                "reference": "https://en.wikipedia.org/wiki/Mawlid",
                "exactDates": "",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "Islam",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Laylat al-Qadr",
                "duration": "1 Night",
                "frequency": "Night of Power (believed to be the night Quran revealed)",
                "effectiveHours": "Varies",
                "reference": "https://en.wikipedia.org/wiki/Night_of_Power",
                "exactDates": "",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "Islam",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Ramadan",
                "duration": "29-30 Days",
                "frequency": "Month of fasting and prayer",
                "effectiveHours": "Varies",
                "reference": "https://en.wikipedia.org/wiki/Ramadan",
                "exactDates": "March 10 - April 8, 2024",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "Islam",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Eid al-Fitr",
                "duration": "3-4 Days",
                "frequency": "Festival of Breaking the Fast (end of Ramadan)",
                "effectiveHours": "Varies",
                "reference": "https://en.wikipedia.org/wiki/Eid_al-Fitr",
                "exactDates": "April 9-10, 2024",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "Islam",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Hajj",
                "duration": "5-6 Days",
                "frequency": "Pilgrimage to Mecca (once in a lifetime for Muslims who are able)",
                "effectiveHours": "Varies",
                "reference": "https://en.wikipedia.org/wiki/Hajj",
                "exactDates": "June 14 - June 19, 2024",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "Islam",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Eid al-Adha",
                "duration": "4 Days",
                "frequency": "Festival of Sacrifice (commemorates Abraham's sacrifice)",
                "effectiveHours": "Varies",
                "reference": "https://en.wikipedia.org/wiki/Eid_al-Adha",
                "exactDates": "June 16-19, 2024",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "Islam",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Arafah (Day of Arafah)",
                "duration": "1 Day",
                "frequency": "Day of standing on Arafah during Hajj",
                "effectiveHours": "Varies",
                "reference": "https://en.wikipedia.org/wiki/Day_of_Arafah",
                "exactDates": "June 15, 2024",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "Islam",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Muharram",
                "duration": "1 Day",
                "frequency": "First month of the Islamic calendar",
                "effectiveHours": "Varies",
                "reference": "https://en.wikipedia.org/wiki/Islamic_calendar",
                "exactDates": "Sunday 7th July 2024",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "Islam",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Shaban",
                "duration": "1 Month",
                "frequency": "Eighth month of the Islamic calendar",
                "effectiveHours": "Varies",
                "reference": "https://en.wikipedia.org/wiki/Sha%27ban",
                "exactDates": "",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "Islam",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Dhul-Hijjah",
                "duration": "1 Month",
                "frequency": "Twelfth month of the Islamic calendar",
                "effectiveHours": "Varies",
                "reference": "https://en.wikipedia.org/wiki/Dhu_al-Hijja",
                "exactDates": "",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "Islam",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Rajab",
                "duration": "1 Month",
                "frequency": "Seventh month of the Islamic calendar",
                "effectiveHours": "Varies",
                "reference": "https://en.wikipedia.org/wiki/Rajab",
                "exactDates": "",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "Islam",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Jummah (Friday Prayer)",
                "duration": "1 Day (Prayer Service)",
                "frequency": "Every Friday",
                "effectiveHours": "Varies",
                "reference": "https://en.wikipedia.org/wiki/Friday_prayer",
                "exactDates": "",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "Islam",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Laylat al-Bara'a (Night of Forgiveness)",
                "duration": "1 Night",
                "frequency": "15th night of Shaban (seeking forgiveness from Allah)",
                "effectiveHours": "Varies",
                "reference": "https://en.wikipedia.org/wiki/Night_of_Power",
                "exactDates": "",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "Islam",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Ashura al-Bara'a (Day of Forgiveness)",
                "duration": "1 Day",
                "frequency": "Follows Laylat al-Bara'a",
                "effectiveHours": "Varies",
                "reference": "https://en.wikipedia.org/wiki/Night_of_Power",
                "exactDates": "",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "Islam",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Mawlid al-Imam Ali (Birthday of Ali)",
                "duration": "1-3 Days",
                "frequency": "Birthday of Imam Ali, son-in-law of Prophet Muhammad",
                "effectiveHours": "Varies",
                "reference": "https://en.wikipedia.org/wiki/Ali",
                "exactDates": "",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "Islam",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Miraj (Night Journey)",
                "duration": "1 Night",
                "frequency": "Night of Prophet Muhammad's journey to Jerusalem and Heaven",
                "effectiveHours": "Varies",
                "reference": "https://en.wikipedia.org/wiki/Isra%27_and_Mi%27raj",
                "exactDates": "",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "Islam",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Isra' wal-Miraj",
                "duration": "1 Night",
                "frequency": "Combination of Night Journey and Ascension to Heaven",
                "effectiveHours": "Varies",
                "reference": "https://en.wikipedia.org/wiki/Isra%27_and_Mi%27raj",
                "exactDates": "",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "Islam",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Eid al-Ghadeer",
                "duration": "1 Day",
                "frequency": "Commemorated with special prayers, sermons, and gatherings, particularly emphasizing the leadership of Imam Ali.",
                "effectiveHours": "Varies",
                "reference": "https://en.wikipedia.org/wiki/Eid_al-Ghadir",
                "exactDates": "18th of Dhu al-Hijjah",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "Islam Shia",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Eid al-Mubahila",
                "duration": "1 Day",
                "frequency": "Marked by special prayers and gatherings to remember the event of Mubahila.",
                "effectiveHours": "Varies",
                "reference": "",
                "exactDates": "24th of Dhu al-Hijjah",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "Islam Shia",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Eid al-Mab'ath",
                "duration": "1 Day",
                "frequency": "Commemorated with prayers, recitation of Quranic verses, and reflections on the significance of Prophet Muhammad's mission.",
                "effectiveHours": "Varies",
                "reference": "",
                "exactDates": "27th of Rajab",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "Islam Shia",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Eid al-Zahra",
                "duration": "1 Day",
                "frequency": "Celebrated with prayers, lectures, and gatherings highlighting the virtues of Fatimah al-Zahra.",
                "effectiveHours": "Varies",
                "reference": "",
                "exactDates": "9th of Rabi' al-Awwal",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "Islam Shia",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Islamic Revolution Victory Day",
                "duration": "1 Day",
                "frequency": "Commemorates the victory of the Iranian Revolution in 1979, leading to the overthrow of the Pahlavi dynasty and the establishment of the Islamic Republic of Iran.",
                "effectiveHours": "Varies",
                "reference": "",
                "exactDates": "22 Bahman/February 11th",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "Iran",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Nowruz",
                "duration": "1 Day",
                "frequency": "Persian New Year, celebrated as the beginning of spring and the first day of the Iranian calendar.",
                "effectiveHours": "1 Farvardin/March 21st",
                "reference": "",
                "exactDates": "",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "Iran",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Islamic Republic Day",
                "duration": "1 Day",
                "frequency": "Marks the anniversary of the establishment of the Islamic Republic of Iran on April 1st, 1979.",
                "effectiveHours": "12 Farvardin/April 1st",
                "reference": "",
                "exactDates": "",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "Iran",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Martyrs' Day",
                "duration": "1 Day",
                "frequency": "Honors those who lost their lives in service to the country, particularly during the Iran-Iraq War (1980-1988) and other conflicts.",
                "effectiveHours": "13 Aban/November 3rd",
                "reference": "",
                "exactDates": "",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "Iran",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Quds Day",
                "duration": "1 Day",
                "frequency": "An annual event initiated by Ayatollah Khomeini to express support for the Palestinian people and opposition to Israel's control over Jerusalem.",
                "effectiveHours": "Last Friday of Ramadan",
                "reference": "",
                "exactDates": "",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "Iran",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Student Day",
                "duration": "1 Day",
                "frequency": "Commemorates the anniversary of the 1953 Iranian student protests against the visit of then U.S. Vice President Richard Nixon to Tehran and the killing of three students by the Shah's forces.",
                "effectiveHours": "16 Azar/December 7th",
                "reference": "",
                "exactDates": "",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "Iran",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Revolution Day",
                "duration": "1 Day",
                "frequency": "Celebrates the victory of the Islamic Revolution in 1979.",
                "effectiveHours": "01-Feb",
                "reference": "",
                "exactDates": "",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "Iran",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Martyrdom of Imam Ali",
                "duration": "1 Day",
                "frequency": "Commemorates the assassination of Imam Ali, the cousin and son-in-law of Prophet Muhammad and the first Imam of Shia Islam.",
                "effectiveHours": "21 Ramadan",
                "reference": "",
                "exactDates": "22 Bahman/February 11th",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "Islam Shia",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Nationalization of Oil Industry Day",
                "duration": "1 Day",
                "frequency": "Marks the anniversary of the nationalization of the Iranian oil industry under the leadership of Prime Minister Mohammad Mossadegh in 1951.",
                "effectiveHours": "20 Esfand/March 11th",
                "reference": "",
                "exactDates": "",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "Iran",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Death Anniversary of Ayatollah Khomeini",
                "duration": "1 Day",
                "frequency": "Commemorates the death of Ayatollah Ruhollah Khomeini, the founder of the Islamic Republic of Iran and the leader of the Iranian Revolution.",
                "effectiveHours": "04-Jun",
                "reference": "",
                "exactDates": "",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "Iran",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Nakba Day",
                "duration": "1 Day",
                "frequency": 'Commemorates the Palestinian exodus, or "Nakba," which occurred following the 1948 Arab-Israeli War, resulting in the displacement of hundreds of thousands of Palestinians from their homes.',
                "effectiveHours": "15-May",
                "reference": "",
                "exactDates": "",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "Palestine",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Land Day",
                "duration": "1 Day",
                "frequency": 'Marks the anniversary of protests and general strikes held in 1976 to protest against Israeli government plans to expropriate land from Palestinian citizens of Israel.',
                "effectiveHours": "30-Mar",
                "reference": "",
                "exactDates": "",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "Palestine",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Prisoner's Day",
                "duration": "1 Day",
                "frequency": 'Honors Palestinian prisoners held in Israeli jails and commemorates their struggles and sacrifices.',
                "effectiveHours": "17-Apr",
                "reference": "",
                "exactDates": "",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "Palestine",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Jerusalem Day",
                "duration": "1 Day",
                "frequency": 'Celebrates the Palestinian and Arab cultural, religious, and historical ties to Jerusalem, particularly in opposition to Israeli control over the city.',
                "effectiveHours": "Last Friday of Ramadan",
                "reference": "",
                "exactDates": "",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "Palestine",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Al-Naksa Day",
                "duration": "1 Day",
                "frequency": 'Commemorates the displacement of Palestinians following the Six-Day War in 1967, during which Israel occupied the West Bank, Gaza Strip, East Jerusalem, and other territories.',
                "effectiveHours": "05-Jun",
                "reference": "",
                "exactDates": "",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "Palestine",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Balfour Declaration Day",
                "duration": "1 Day",
                "frequency": 'Marks the anniversary of the Balfour Declaration issued in 1917 by the British government, which expressed support for the establishment of a "national home for the Jewish people" in Palestine.',
                "effectiveHours": "02-Nov",
                "reference": "",
                "exactDates": "",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "Palestine",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Gaza Flotilla Raid Anniversary",
                "duration": "1 Day",
                "frequency": 'Remembers the raid by Israeli forces on a flotilla of ships attempting to break the Israeli blockade of the Gaza Strip in 2010, resulting in several deaths and international condemnation.',
                "effectiveHours": "15-May",
                "reference": "",
                "exactDates": "",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "Palestine",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Nakba Day",
                "duration": "1 Day",
                "frequency": 'Commemorates the Palestinian exodus, or "Nakba," which occurred following the 1948 Arab-Israeli War, resulting in the displacement of hundreds of thousands of Palestinians from their homes.',
                "effectiveHours": "31-May",
                "reference": "",
                "exactDates": "",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "Palestine",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Great March of Return",
                "duration": "15 days",
                "frequency": 'A series of protests and demonstrations along the Gaza-Israel border, calling for the right of return for Palestinian refugees and an end to the Israeli blockade of Gaza.',
                "effectiveHours": "30 March - 15 May",
                "reference": "",
                "exactDates": "",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "Palestine",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "International Day of Solidarity with the Palestinian People",
                "duration": "1 Day",
                "frequency": 'Recognized by the United Nations, this day aims to promote awareness and support for the Palestinian cause.',
                "effectiveHours": "29-Nov",
                "reference": "",
                "exactDates": "",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "Palestine",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Martyr's Day",
                "duration": "1 Day",
                "frequency": 'Honors Palestinian martyrs who have died in the struggle for Palestinian rights and independence.',
                "effectiveHours": "07-Apr",
                "reference": "",
                "exactDates": "",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "Palestine",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Palestinian Children's Day",
                "duration": "1 Day",
                "frequency": 'Raises awareness about the rights and well-being of Palestinian children, who often face violence, displacement, and discrimination.',
                "effectiveHours": "05-Apr",
                "reference": "",
                "exactDates": "",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "Palestine",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Al-Aqsa Intifada Anniversary",
                "duration": "1 Day",
                "frequency": 'Marks the beginning of the second Palestinian uprising in 2000, triggered by a visit by then-Israeli opposition leader Ariel Sharon to the Al-Aqsa Mosque compound in Jerusalem.',
                "effectiveHours": "28-Sep",
                "reference": "",
                "exactDates": "",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "Palestine",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Gaza's Independence Day",
                "duration": "1 Day",
                "frequency": 'A day to celebrate Gaza"s resistance against Israeli occupation and its right to self-determination.',
                "effectiveHours": "26-Aug",
                "reference": "",
                "exactDates": "",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "Palestine",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Armed Struggle Day",
                "duration": "1 Day",
                "frequency": 'A day to honor Palestinian resistance fighters and their sacrifices in the struggle against Israeli occupation and colonization.',
                "effectiveHours": "09-Dec",
                "reference": "",
                "exactDates": "",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "Palestine",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Palestinian Youth Day",
                "duration": "1 Day",
                "frequency": 'A day to celebrate the role of Palestinian youth in the struggle for freedom, justice, and self-determination.',
                "effectiveHours": "12-Aug",
                "reference": "",
                "exactDates": "",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "Palestine",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Jenin Martyrs' Day",
                "duration": "1 Day",
                "frequency": 'A day to remember and honor the martyrs of the Israeli massacre in the Jenin refugee camp in 2002, and to reaffirm the Palestinian right to resist occupation.',
                "effectiveHours": "09-Apr",
                "reference": "",
                "exactDates": "",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "Palestine",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Right to Education Day",
                "duration": "1 Day",
                "frequency": 'A day to highlight the challenges faced by Palestinian students and educators under Israeli occupation, including attacks on schools, restrictions on movement, and lack of resources.',
                "effectiveHours": "24-Jan",
                "reference": "",
                "exactDates": "",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "Palestine",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Palestinian Cultural Heritage Day",
                "duration": "1 Day",
                "frequency": 'A day to celebrate Palestinian culture, heritage, and identity, and to resist Israeli efforts to erase or appropriate Palestinian history and heritage.',
                "effectiveHours": "18-Nov",
                "reference": "",
                "exactDates": "",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "Palestine",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Day of the Palestinian Woman",
                "duration": "1 Day",
                "frequency": 'A day to celebrate the role of Palestinian women in the struggle for freedom, justice, and equality, and to highlight their contributions to Palestinian society.',
                "effectiveHours": "08-Mar",
                "reference": "",
                "exactDates": "",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "Palestine",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Day of the Palestinian Farmer",
                "duration": "1 Day",
                "frequency": 'A day to honor Palestinian farmers and their steadfastness in the face of Israeli land confiscation, settlement expansion, and agricultural destruction.',
                "effectiveHours": "25-Oct",
                "reference": "",
                "exactDates": "",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "Palestine",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Cedar Revolution Anniversary",
                "duration": "1 Day",
                "frequency": 'Commemorative events, including speeches, gatherings, and sometimes protests, may take place throughout the day, particularly in the evening.',
                "effectiveHours": "14-Feb",
                "reference": "",
                "exactDates": "",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "Lebanon",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Kidnapped Sheikh Abdel Karim Obeid",
                "duration": "1 Day",
                "frequency": 'On 28 July 1989, Israeli commandos kidnapped Sheikh Abdel Karim Obeid, the leader of Hezbollah.',
                "effectiveHours": "28-Jul",
                "reference": "https://en.wikipedia.org/wiki/Hezbollah",
                "exactDates": "",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "Hezbollah",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Assassination of Abbas al-Musawi",
                "duration": "1 Day",
                "frequency": 'On 16 February 1992, Israeli helicopters attacked a motorcade in southern Lebanon, killing the Hezbollah leader Abbas al-Musawi, his wife, son, and four others.',
                "effectiveHours": "16-Feb",
                "reference": "https://en.wikipedia.org/wiki/Hezbollah",
                "exactDates": "",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "Hezbollah",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Assassination of Rida Yasin",
                "duration": "1 Day",
                "frequency": 'On 31 March 1995, Rida Yasin, also known as Abu Ali, was killed by a single rocket fired from an Israeli helicopter while in a car near Derdghaya in the Israeli security zone 10 km east of Tyre. Yasin was a senior military commander in southern Lebanon.',
                "effectiveHours": "31-Mar",
                "reference": "https://en.wikipedia.org/wiki/Hezbollah",
                "exactDates": "",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "Hezbollah",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Assasination of Imad Mughnieh",
                "duration": "1 Day",
                "frequency": 'On 12 February 2008, Imad Mughnieh was killed by a car bomb in Damascus, Syria.',
                "effectiveHours": "12-Feb",
                "reference": "https://en.wikipedia.org/wiki/Hezbollah",
                "exactDates": "",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "Hezbollah",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Madrid Train Bombings",
                "duration": "1 Day",
                "frequency": 'Coordinated bombings targeting commuter trains in Madrid, Spain, killed 191 people and injured over 2,000 others.',
                "effectiveHours": "11-Mar-04",
                "reference": "",
                "exactDates": "",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "World Wide Attacks",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "London Bombings",
                "duration": "1 Day",
                "frequency": 'A series of coordinated suicide bombings targeting London"s public transportation system, including three underground trains and one double-decker bus, resulted in 52 deaths and over 700 injuries.',
                "effectiveHours": "07-Jul-05",
                "reference": "",
                "exactDates": "",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "World Wide Attacks",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Paris Attacks",
                "duration": "1 Day",
                "frequency": 'A series of coordinated terrorist attacks occurred in Paris, France, targeting multiple locations including the Bataclan theater, Stade de France, and various restaurants and bars, resulting in 130 deaths and hundreds of injuries.',
                "effectiveHours": "13-Nov-15",
                "reference": "",
                "exactDates": "",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "World Wide Attacks",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Brussels Bombings",
                "duration": "1 Day",
                "frequency": 'Coordinated suicide bombings targeted Brussels Airport and a metro station in central Brussels, Belgium, resulting in 32 deaths and over 300 injuries.',
                "effectiveHours": "22-Mar-16",
                "reference": "",
                "exactDates": "",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "World Wide Attacks",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Manchester Arena Bombing",
                "duration": "1 Day",
                "frequency": 'A suicide bombing occurred at the Manchester Arena in Manchester, United Kingdom, following a concert by Ariana Grande, resulting in 22 deaths and hundreds of injuries, mostly young concertgoers.',
                "effectiveHours": "22-May-17",
                "reference": "",
                "exactDates": "",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "World Wide Attacks",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Nice Truck Attack",
                "duration": "1 Day",
                "frequency": 'A truck was deliberately driven into crowds celebrating Bastille Day on the Promenade des Anglais in Nice, France, resulting in 86 deaths and over 400 injuries.',
                "effectiveHours": "14-Jul-16",
                "reference": "",
                "exactDates": "",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "World Wide Attacks",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Berlin Christmas Market Attack",
                "duration": "1 Day",
                "frequency": 'A truck was driven into a Christmas market at Breitscheidplatz in Berlin, Germany, killing 12 people and injuring 56 others.',
                "effectiveHours": "19-Dec-16",
                "reference": "",
                "exactDates": "",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "World Wide Attacks",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Stockholm Truck Attack",
                "duration": "1 Day",
                "frequency": 'A hijacked truck was driven into pedestrians on Drottninggatan, a busy shopping street in Stockholm, Sweden, resulting in 5 deaths and several injuries.',
                "effectiveHours": "07-Apr-17",
                "reference": "",
                "exactDates": "",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "World Wide Attacks",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Westminster Bridge Attack",
                "duration": "1 Day",
                "frequency": 'A vehicle was driven into pedestrians on Westminster Bridge in London, United Kingdom, before crashing into the perimeter fence of the Palace of Westminster. The attacker then fatally stabbed a police officer before being shot dead by police. Five people were killed, including the assailant, and around 50 others were injured.',
                "effectiveHours": "22-Mar-17",
                "reference": "",
                "exactDates": "",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "World Wide Attacks",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "London Bridge and Borough Market Attack",
                "duration": "1 Day",
                "frequency": 'A van was driven into pedestrians on London Bridge, followed by stabbings in nearby Borough Market, London, United Kingdom. Eight people were killed and 48 others were injured before the attackers were shot dead by police.',
                "effectiveHours": "03-Jun-17",
                "reference": "",
                "exactDates": "",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "World Wide Attacks",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Vienna Shooting",
                "duration": "1 Day",
                "frequency": 'Multiple gunmen opened fire in the inner city of Vienna, Austria, targeting bars and restaurants. Four people were killed, including the attacker, and over 20 others were injured.',
                "effectiveHours": "02-Nov-20",
                "reference": "",
                "exactDates": "",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "World Wide Attacks",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "Nice Basilica Attack",
                "duration": "1 Day",
                "frequency": 'A knife-wielding attacker killed three people and injured several others in a terrorist attack at the Notre-Dame Basilica in Nice, France.',
                "effectiveHours": "29-Oct-20",
                "reference": "",
                "exactDates": "",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "World Wide Attacks",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            },
            {
                "holiday": "September 11 attacks",
                "duration": "1 Day",
                "frequency": 'The September 11 attacks, commonly known as 9/11, were four coordinated Islamist suicide terrorist attacks carried out by al-Qaeda against the United States on September 11, 2001.',
                "effectiveHours": "11-Sep",
                "reference": "https://en.wikipedia.org/wiki/September_11_attacks",
                "exactDates": "",
                "related": {},
                "policyScore": "low",
                "justification": "",
                "religion": "World Wide Attacks",
                "type": "",
                "relatedEntities": {},
                "createDate": ""
            }
        ],
        "widgetType": "CALENDAR_TABLE",
        "actionKey": "km_calender"
    }
}
